import { z } from "zod";
import { OpaqueIdSchema } from "./ids";
import { RunPhaseSchema } from "./run";

export const C0_FIXTURE_WARNING =
  "This artifact was generated by the C0 deterministic fixture stage and does not represent real customer discovery.";

export const ArtifactTypeSchema = z.enum([
  "mission",
  "interpretation",
  "source_plan",
  "search_results",
  "candidates",
  "investigations",
  "buyers",
  "contacts",
  "opportunities",
  "review",
  "finalization",
]);
export type ArtifactType = z.infer<typeof ArtifactTypeSchema>;

export const FixtureArtifactEnvelopeSchema = z
  .object({
    schemaVersion: z.literal("1.0"),
    fixture: z.literal(true),
    warning: z.literal(C0_FIXTURE_WARNING),
    stage: RunPhaseSchema,
    runId: OpaqueIdSchema,
    generatedAt: z.iso.datetime({ offset: true }),
    data: z.record(z.string(), z.unknown()),
  })
  .strict();
export type FixtureArtifactEnvelope = z.infer<typeof FixtureArtifactEnvelopeSchema>;

export const ArtifactRecordSchema = z
  .object({
    id: OpaqueIdSchema,
    runId: OpaqueIdSchema,
    artifactType: ArtifactTypeSchema,
    schemaVersion: z.string().min(1),
    version: z.number().int().positive(),
    stage: RunPhaseSchema,
    contentHash: z.string().regex(/^[a-f0-9]{64}$/),
    fileName: z.string().min(1),
    data: z.unknown(),
    createdAt: z.iso.datetime({ offset: true }),
  })
  .strict();
export type ArtifactRecord = z.infer<typeof ArtifactRecordSchema>;

export const ARTIFACT_FILE_NAMES: Readonly<Record<ArtifactType, string>> = {
  mission: "00-mission.json",
  interpretation: "01-interpretation.json",
  source_plan: "02-source-plan.json",
  search_results: "03-search-results.json",
  candidates: "04-candidates.json",
  investigations: "05-investigations.json",
  buyers: "06-buyers.json",
  contacts: "07-contacts.json",
  opportunities: "08-opportunities.json",
  review: "09-review.json",
  finalization: "10-finalization.json",
};
