import { z } from "zod";
import { OpaqueIdSchema } from "./ids";
import { RunPhaseSchema } from "./run";

export const C0_FIXTURE_WARNING =
  "This artifact was generated by the C0 deterministic fixture stage and does not represent real customer discovery.";

export const ArtifactTypeSchema = z.enum([
  "mission",
  "interpretation",
  "mission_understanding",
  "source_plan",
  "search_results",
  "crawl_frontier",
  "extracted_content",
  "extraction_telemetry",
  "structured_content",
  "content_parse_telemetry",
  "candidates",
  "investigations",
  "evidence_findings",
  "buyers",
  "contacts",
  "identity_enrichment",
  "opportunities",
  "ranked_opportunities",
  "review",
  "buyer_map",
  "finalization",
]);
export type ArtifactType = z.infer<typeof ArtifactTypeSchema>;

export const FixtureArtifactEnvelopeSchema = z
  .object({
    schemaVersion: z.literal("1.0"),
    fixture: z.literal(true),
    warning: z.literal(C0_FIXTURE_WARNING),
    stage: RunPhaseSchema,
    runId: OpaqueIdSchema,
    generatedAt: z.iso.datetime({ offset: true }),
    data: z.record(z.string(), z.unknown()),
  })
  .strict();
export type FixtureArtifactEnvelope = z.infer<typeof FixtureArtifactEnvelopeSchema>;

export const ArtifactRecordSchema = z
  .object({
    id: OpaqueIdSchema,
    runId: OpaqueIdSchema,
    artifactType: ArtifactTypeSchema,
    schemaVersion: z.string().min(1),
    version: z.number().int().positive(),
    stage: RunPhaseSchema,
    contentHash: z.string().regex(/^[a-f0-9]{64}$/),
    fileName: z.string().min(1),
    data: z.unknown(),
    createdAt: z.iso.datetime({ offset: true }),
  })
  .strict();
export type ArtifactRecord = z.infer<typeof ArtifactRecordSchema>;

export const ARTIFACT_FILE_NAMES: Readonly<Record<ArtifactType, string>> = {
  mission: "00-mission.json",
  interpretation: "01-interpretation.json",
  mission_understanding: "01-mission-understanding.json",
  source_plan: "02-source-plan.json",
  search_results: "03-search-results.json",
  crawl_frontier: "04-crawl-frontier.json",
  extracted_content: "05-extracted-content.json",
  extraction_telemetry: "06-extraction-telemetry.json",
  structured_content: "06a-structured-content.json",
  content_parse_telemetry: "06b-content-parse-telemetry.json",
  candidates: "07-candidates.json",
  investigations: "08-investigations.json",
  evidence_findings: "08-evidence-findings.json",
  buyers: "09-buyers.json",
  contacts: "10-contacts.json",
  identity_enrichment: "10-identity-enrichment.json",
  opportunities: "11-opportunities.json",
  ranked_opportunities: "11-ranked-opportunities.json",
  review: "12-review.json",
  buyer_map: "12-buyer-map.json",
  finalization: "13-finalization.json",
};
