import {
  canonicalDigest,
  deterministicArtifactId,
  sha256Hex,
} from "../extraction/artifact-identity";
import type {
  TranscriptArtifactV1,
  TranscriptManifestArtifactV1,
  VideoCollectionArtifactV1,
  VideoCommentCollectionArtifactV1,
  VideoCommentManifestArtifactV1,
  VideoSignalsArtifactV1,
  VideoSourcePlanArtifactV1,
  VideoSourceRunTelemetryArtifactV1,
} from "./video-artifacts";

function deterministicId<T extends { requestId: string; artifactKind: string }>(
  artifact: Omit<T, "artifactId">,
): string {
  return deterministicArtifactId(artifact.requestId, artifact.artifactKind, artifact);
}

export const videoArtifactDigest = canonicalDigest;
export const deterministicVideoSourcePlanId = (
  artifact: Omit<VideoSourcePlanArtifactV1, "artifactId">,
): string => deterministicId(artifact);
export const deterministicVideoCollectionId = (
  artifact: Omit<VideoCollectionArtifactV1, "artifactId">,
): string => deterministicId(artifact);
export const deterministicTranscriptManifestId = (
  artifact: Omit<TranscriptManifestArtifactV1, "artifactId">,
): string => deterministicId(artifact);
export const deterministicVideoCommentCollectionId = (
  artifact: Omit<VideoCommentCollectionArtifactV1, "artifactId">,
): string => deterministicId(artifact);
export const deterministicVideoCommentManifestId = (
  artifact: Omit<VideoCommentManifestArtifactV1, "artifactId">,
): string => deterministicId(artifact);
export const deterministicVideoSignalsId = (
  artifact: Omit<VideoSignalsArtifactV1, "artifactId">,
): string => deterministicId(artifact);
export const deterministicVideoTelemetryId = (
  artifact: Omit<VideoSourceRunTelemetryArtifactV1, "artifactId">,
): string => deterministicId(artifact);

export function deterministicVideoQueryId(input: {
  requestId: string;
  intent: string;
  query: string;
}): string {
  return `video_query_${sha256Hex([input.requestId, input.intent, input.query.trim().toLowerCase()].join("\n"))}`;
}

export function deterministicTranscriptId(input: {
  requestId: string;
  videoId: string;
  language: string;
  autoGenerated: boolean;
  segments: TranscriptArtifactV1["segments"];
}): string {
  return deterministicArtifactId(input.requestId, "transcript.v1", {
    videoId: input.videoId,
    language: input.language,
    autoGenerated: input.autoGenerated,
    segments: input.segments,
  });
}

export function deterministicTranscriptSegmentId(input: {
  videoId: string;
  sequence: number;
  startSeconds?: number;
  endSeconds?: number;
  text: string;
}): string {
  return `video_segment_${sha256Hex(
    [
      input.videoId,
      String(input.sequence),
      String(input.startSeconds ?? ""),
      String(input.endSeconds ?? ""),
      input.text.trim(),
    ].join("\n"),
  )}`;
}

export function deterministicVideoCommentId(input: {
  videoId: string;
  sourceNativeId?: string;
  parentCommentId?: string;
  body: string;
}): string {
  return `video_comment_${sha256Hex(
    [
      input.videoId,
      input.sourceNativeId ?? "",
      input.parentCommentId ?? "",
      input.body.trim(),
    ].join("\n"),
  )}`;
}

export function deterministicVideoSignalId(input: {
  requestId: string;
  type: string;
  ruleId: string;
  videoIds: string[];
  segmentIds: string[];
  commentIds: string[];
}): string {
  return `video_signal_${sha256Hex(
    [
      input.requestId,
      input.type,
      input.ruleId,
      [...new Set(input.videoIds)].sort().join(","),
      [...new Set(input.segmentIds)].sort().join(","),
      [...new Set(input.commentIds)].sort().join(","),
    ].join("\n"),
  )}`;
}
