import {
  CluvviSourceFamilySchema,
  LocalDiscoveryExecutionRecordV1Schema,
  RunPhaseSchema,
  deterministicSpecializedContextId,
  deterministicVideoCollectionId,
  deterministicVideoSourcePlanId,
  SpecializedSourceContextArtifactV1Schema,
  SpecializedSourcePlanArtifactV1Schema,
  SpecializedSourceRunTelemetryArtifactV1Schema,
  TranscriptArtifactV1Schema,
  VideoCollectionArtifactV1Schema,
  VideoSourcePlanArtifactV1Schema,
  VideoSourceRunTelemetryArtifactV1Schema,
  validateSpecializedContextArtifact,
  validateVideoCollectionSet,
  validateVideoPlanArtifact,
} from "@cluvvi/core";
import { describe, expect, it } from "vitest";

describe("C1-J.4/J.5 Project B bridge contracts", () => {
  it("accepts video and specialized as source families and rejects research", () => {
    expect(CluvviSourceFamilySchema.parse("video")).toBe("video");
    expect(CluvviSourceFamilySchema.parse("specialized")).toBe("specialized");
    expect(() => CluvviSourceFamilySchema.parse("research")).toThrow();
  });

  it("parses the frozen transcript.v1 shape independently in Project B", () => {
    expect(
      TranscriptArtifactV1Schema.parse({
        schemaVersion: "1.0",
        artifactKind: "transcript.v1",
        artifactId: "transcript_test",
        requestId: "request_test",
        sourceAdapterId: "youtube_transcript_ytdlp",
        sourceNativeId: "abc123xyz",
        mediaUrl: "https://www.youtube.com/watch?v=abc123xyz",
        language: "en",
        autoGenerated: true,
        durationSeconds: 10,
        segments: [
          {
            segmentId: "segment_1",
            sequence: 0,
            startSeconds: 0,
            endSeconds: 2,
            text: "Public transcript evidence.",
            contentHash: "a".repeat(64),
          },
        ],
        trustClassification: "untrusted_public_content",
        limitations: ["Automatic caption evidence."],
      }).artifactKind,
    ).toBe("transcript.v1");
  });

  it("validates deterministic video plans and refuses forbidden imported secret fields", () => {
    const withoutId = {
      schemaVersion: "1.0" as const,
      artifactKind: "video_source_plan.v1" as const,
      requestId: "request_test",
      sourceFamily: "video" as const,
      platform: "youtube" as const,
      temporalWindow: {},
      queries: [],
      policy: {
        depth: "default" as const,
        maximumQueries: 4,
        maximumSearchResults: 30,
        maximumMetadataDetails: 15,
        maximumTranscriptDrill: 5,
        maximumCommentVideos: 3,
        maximumCommentsPerVideo: 20,
      },
      summary: { queryCandidates: 0, queriesSelected: 0 },
      warnings: [],
    };
    const artifact = VideoSourcePlanArtifactV1Schema.parse({
      ...withoutId,
      artifactId: deterministicVideoSourcePlanId(withoutId),
    });
    const valid = validateVideoPlanArtifact(artifact);
    expect(valid.plan.requestId).toBe("request_test");
    expect(() =>
      validateVideoPlanArtifact({
        ...artifact,
        artifactId: "placeholder",
        authorizationToken: "secret",
      }),
    ).toThrow(/forbidden|private|secret/iu);
  });

  it("allows restricted video metadata to cross only when it is never drilled or used as transcript/comment evidence", () => {
    const planWithoutId = {
      schemaVersion: "1.0" as const,
      artifactKind: "video_source_plan.v1" as const,
      requestId: "request_restricted_metadata",
      sourceFamily: "video" as const,
      platform: "youtube" as const,
      temporalWindow: {},
      queries: [],
      policy: {
        depth: "quick" as const,
        maximumQueries: 2,
        maximumSearchResults: 10,
        maximumMetadataDetails: 5,
        maximumTranscriptDrill: 1,
        maximumCommentVideos: 1,
        maximumCommentsPerVideo: 5,
      },
      summary: { queryCandidates: 0, queriesSelected: 0 },
      warnings: [],
    };
    const plan = VideoSourcePlanArtifactV1Schema.parse({
      ...planWithoutId,
      artifactId: deterministicVideoSourcePlanId(planWithoutId),
    });
    const collectionWithoutId = {
      schemaVersion: "1.0" as const,
      artifactKind: "video_collection.v1" as const,
      requestId: plan.requestId,
      videoSourcePlanArtifactId: plan.artifactId,
      videos: [
        {
          videoId: "abc123xyz",
          sourceNativeId: "abc123xyz",
          url: "https://www.youtube.com/watch?v=abc123xyz",
          title: "Unavailable metadata candidate",
          tags: [],
          categories: [],
          liveStatus: "unknown" as const,
          availability: "private" as const,
          ageRestricted: false,
          subtitles: [],
          relevance: 0.5,
          temporalConfidence: 0.5,
          localScore: 0.5,
          selectedForTranscript: false,
          selectedForComments: false,
          trustClassification: "untrusted_public_content" as const,
          provenance: [
            {
              adapterId: "youtube_video_metadata_ytdlp",
              method: "youtube_metadata" as const,
              observedAt: "2026-08-10T00:00:00.000Z",
            },
          ],
          limitations: ["Private/unavailable item is metadata-only and cannot be drilled."],
        },
      ],
      summary: {
        searchCandidates: 1,
        videosAccepted: 1,
        duplicatesRemoved: 0,
        metadataDetailsFetched: 1,
        videosWithHumanSubtitles: 0,
        videosWithAutomaticCaptions: 0,
        videosWithKnownViews: 0,
        videosWithKnownLikes: 0,
      },
      warnings: [],
      limitations: ["Restricted metadata is retained only to record bounded discovery state."],
    };
    const collection = VideoCollectionArtifactV1Schema.parse({
      ...collectionWithoutId,
      artifactId: deterministicVideoCollectionId(collectionWithoutId),
    });
    expect(
      validateVideoCollectionSet({ planSet: { plan }, collection }).collection.videos,
    ).toHaveLength(1);
    const selectedRestrictedWithoutId = {
      schemaVersion: collection.schemaVersion,
      artifactKind: collection.artifactKind,
      requestId: collection.requestId,
      videoSourcePlanArtifactId: collection.videoSourcePlanArtifactId,
      videos: [{ ...collection.videos[0]!, selectedForTranscript: true }],
      summary: collection.summary,
      warnings: collection.warnings,
      limitations: collection.limitations,
    };
    const selectedRestricted = VideoCollectionArtifactV1Schema.parse({
      ...selectedRestrictedWithoutId,
      artifactId: deterministicVideoCollectionId(selectedRestrictedWithoutId),
    });
    expect(() =>
      validateVideoCollectionSet({ planSet: { plan }, collection: selectedRestricted }),
    ).toThrow(/restricted|non-public|transcript|drill/iu);
  });

  it("parses specialized context/plan/telemetry with specialized as the only family name", () => {
    const withoutId = {
      schemaVersion: "1.0" as const,
      artifactKind: "specialized_source_context.v1" as const,
      requestId: "request_test",
      industries: [{ industryId: "human_resources", label: "Human resources", confidence: 0.9 }],
      subIndustries: [],
      geographies: [
        { type: "country" as const, code: "GB", label: "United Kingdom", confidence: 1 },
      ],
      desiredSignals: [
        {
          signalType: "compliance_guidance" as const,
          importance: 0.9,
          concepts: ["employment law"],
        },
      ],
      entityHints: [],
      languagePreferences: ["en"],
      derivation: {
        sourceArtifactKind: "discovery_request.v1" as const,
        sourceRequestId: "request_test",
        rulesVersion: "c1-j5.specialized-context.v1",
      },
      limitations: [],
    };
    const context = SpecializedSourceContextArtifactV1Schema.parse({
      ...withoutId,
      artifactId: deterministicSpecializedContextId(withoutId),
    });
    expect(validateSpecializedContextArtifact(context).context.artifactKind).toBe(
      "specialized_source_context.v1",
    );
    expect(SpecializedSourcePlanArtifactV1Schema.shape.sourceFamily.parse("specialized")).toBe(
      "specialized",
    );
    expect(() =>
      SpecializedSourcePlanArtifactV1Schema.shape.sourceFamily.parse("research"),
    ).toThrow();
    expect(SpecializedSourceRunTelemetryArtifactV1Schema.shape.paidCredits.parse(0)).toBe(0);
  });

  it("keeps video telemetry zero-paid by contract", () => {
    expect(VideoSourceRunTelemetryArtifactV1Schema.shape.paidRequests.parse(0)).toBe(0);
    expect(() => VideoSourceRunTelemetryArtifactV1Schema.shape.paidRequests.parse(1)).toThrow();
  });

  it("defines twelve durable J.4/J.5 phases and an execution record that can persist all five families", () => {
    for (const phase of [
      "video_planning",
      "video_retrieval",
      "video_transcript_retrieval",
      "video_comment_retrieval",
      "video_analysis",
      "video_source_telemetry",
      "specialized_context",
      "specialized_candidate_discovery",
      "specialized_planning",
      "specialized_retrieval",
      "specialized_analysis",
      "specialized_source_telemetry",
    ] as const) {
      expect(RunPhaseSchema.parse(phase)).toBe(phase);
    }
    const record = LocalDiscoveryExecutionRecordV1Schema.parse({
      schemaVersion: "1.0",
      artifactKind: "local_discovery_execution.v1",
      runId: `run_${"a".repeat(32)}`,
      requestId: "request_test",
      projectPath: "C:\\project-a",
      projectCommitSha: "a".repeat(40),
      command: "pnpm",
      arguments: [],
      providerMode: "fixture_only",
      providerPolicy: "free_only",
      sourceAdapterMode: "selected_sources",
      sourceFamilies: ["hiring", "community", "developer", "video", "specialized"],
      youtubeDepth: "default",
      videoSignalRuleVersion: "c1-j4.video-signals.v1",
      specializedSignalRuleVersion: "c1-j5.specialized-signals.v1",
      startedAt: "2026-08-10T00:00:00+00:00",
      timedOut: false,
      cancelled: false,
      requestPath: "request.json",
      outputPath: "search-results.v2.json",
      stdoutPath: "stdout.log",
      stderrPath: "stderr.log",
      videoSourcePlanPath: "video-source-plan.v1.json",
      videoSourcePlanImported: false,
      videoCollectionPath: "video-collection.v1.json",
      videoCollectionImported: false,
      transcriptManifestPath: "transcript-manifest.v1.json",
      transcriptManifestImported: false,
      videoCommentManifestPath: "video-comment-manifest.v1.json",
      videoCommentManifestImported: false,
      videoSignalsPath: "video-signals.v1.json",
      videoSignalsImported: false,
      videoSourceTelemetryPath: "video-source-run-telemetry.v1.json",
      videoSourceTelemetryImported: false,
      videoTranscriptsDirectory: "video/transcripts",
      videoCommentsDirectory: "video/comments",
      specializedSourceContextPath: "specialized-source-context.v1.json",
      specializedSourceContextImported: false,
      specializedSourceCandidatesPath: "specialized-source-candidates.v1.json",
      specializedSourceCandidatesImported: false,
      specializedSourcePlanPath: "specialized-source-plan.v1.json",
      specializedSourcePlanImported: false,
      specializedFindingsPath: "specialized-findings.v1.json",
      specializedFindingsImported: false,
      specializedSignalsPath: "specialized-signals.v1.json",
      specializedSignalsImported: false,
      specializedSourceTelemetryPath: "specialized-source-run-telemetry.v1.json",
      specializedSourceTelemetryImported: false,
      success: true,
    });
    expect(record.sourceFamilies).toHaveLength(5);
  });
});
